
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author AlumnosInf
 */
public class frmPedido extends javax.swing.JFrame {
    String ing[]= {"Palta", "Tomate","Chucrut","Salsa Americana"};
    int precio [] = {500,400,300,200};
    /**
     * Creates new form frmPedido
     */
    public frmPedido() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgTamano = new javax.swing.ButtonGroup();
        jPanel2 = new javax.swing.JPanel();
        cmdSalir = new javax.swing.JButton();
        lblTitulo = new javax.swing.JLabel();
        lblNombre = new javax.swing.JLabel();
        lblTelefono = new javax.swing.JLabel();
        lblDireccion = new javax.swing.JLabel();
        lblIngredientes = new javax.swing.JLabel();
        chkPalta = new javax.swing.JCheckBox();
        chkTomate = new javax.swing.JCheckBox();
        chkChucrut = new javax.swing.JCheckBox();
        chkSalsa = new javax.swing.JCheckBox();
        txtNombre = new javax.swing.JTextField();
        txtTelefono = new javax.swing.JTextField();
        txtDireccion = new javax.swing.JTextField();
        lblTamano = new javax.swing.JLabel();
        rdbNormal = new javax.swing.JRadioButton();
        rdbGrande = new javax.swing.JRadioButton();
        lblPago = new javax.swing.JLabel();
        cmbPago = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstSucursal = new javax.swing.JList<>();
        cmdPedido = new javax.swing.JButton();
        txtPalta = new javax.swing.JTextField();
        txtTomate = new javax.swing.JTextField();
        txtChucrut = new javax.swing.JTextField();
        txtSalsa = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        pswVentana = new javax.swing.JPasswordField();
        jLabel2 = new javax.swing.JLabel();
        cmdVentana = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(800, 700));
        setPreferredSize(new java.awt.Dimension(800, 700));
        getContentPane().setLayout(null);

        jPanel2.setBackground(new java.awt.Color(204, 255, 204));

        cmdSalir.setMnemonic('s');
        cmdSalir.setText("Salir");
        cmdSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdSalirActionPerformed(evt);
            }
        });

        lblTitulo.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(0, 0, 204));
        lblTitulo.setText("Completon");

        lblNombre.setText("Nombre");

        lblTelefono.setText("Telefono");

        lblDireccion.setText("Direccion");

        lblIngredientes.setText("Ingredientes");

        chkPalta.setText("Palta");
        chkPalta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkPaltaActionPerformed(evt);
            }
        });

        chkTomate.setText("Tomate");

        chkChucrut.setText("Chucrut");
        chkChucrut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkChucrutActionPerformed(evt);
            }
        });

        chkSalsa.setText("Salsa Americana");
        chkSalsa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkSalsaActionPerformed(evt);
            }
        });

        txtNombre.setPreferredSize(new java.awt.Dimension(200, 30));

        txtTelefono.setPreferredSize(new java.awt.Dimension(200, 30));
        txtTelefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTelefonoActionPerformed(evt);
            }
        });

        txtDireccion.setPreferredSize(new java.awt.Dimension(200, 30));
        txtDireccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDireccionActionPerformed(evt);
            }
        });

        lblTamano.setText("Tamaño");

        bgTamano.add(rdbNormal);
        rdbNormal.setText("Normal");
        rdbNormal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbNormalActionPerformed(evt);
            }
        });

        bgTamano.add(rdbGrande);
        rdbGrande.setText("Grande");

        lblPago.setText("Pago");

        cmbPago.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Efectivo", "Credito", "Debito" }));

        lstSucursal.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Viña del Mar", "Con Con", "Valparaiso" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(lstSucursal);

        cmdPedido.setText("Pedido");
        cmdPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdPedidoActionPerformed(evt);
            }
        });

        jLabel1.setText("Cantidad");

        jLabel2.setText("Pass");

        cmdVentana.setText("Ventana");
        cmdVentana.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdVentanaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblIngredientes)
                                    .addComponent(lblNombre)
                                    .addComponent(lblTelefono)
                                    .addComponent(lblDireccion))
                                .addGap(42, 42, 42)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addComponent(chkPalta)
                                                .addGap(165, 165, 165)
                                                .addComponent(lblTamano))
                                            .addComponent(chkTomate)
                                            .addComponent(chkChucrut))
                                        .addGap(30, 30, 30)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(rdbGrande)
                                            .addComponent(rdbNormal))
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                                        .addComponent(chkSalsa)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(txtSalsa, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGap(0, 0, Short.MAX_VALUE))
                                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                                        .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                                                        .addComponent(lblPago)))
                                                .addGap(18, 18, 18))
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addComponent(txtPalta, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                            .addComponent(txtDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                            .addComponent(txtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addComponent(txtTomate, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(txtChucrut, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addComponent(jLabel1))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(cmbPago, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addGap(35, 35, 35)
                                                .addComponent(cmdVentana))
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addComponent(jLabel2)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(pswVentana, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(cmdPedido)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(330, 330, 330)
                        .addComponent(lblTitulo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(cmdSalir)
                .addGap(115, 115, 115))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(137, 137, 137)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblNombre)
                                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblPago)
                                    .addComponent(cmbPago, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblTelefono)
                                    .addComponent(txtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(20, 20, 20)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblDireccion)
                                    .addComponent(txtDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addComponent(lblTitulo)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addGap(2, 2, 2)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblIngredientes)
                    .addComponent(chkPalta)
                    .addComponent(lblTamano)
                    .addComponent(rdbNormal)
                    .addComponent(txtPalta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chkTomate)
                    .addComponent(rdbGrande)
                    .addComponent(txtTomate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chkChucrut)
                    .addComponent(txtChucrut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chkSalsa)
                    .addComponent(txtSalsa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pswVentana, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addComponent(cmdVentana)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 167, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmdSalir)
                    .addComponent(cmdPedido))
                .addGap(76, 76, 76))
        );

        getContentPane().add(jPanel2);
        jPanel2.setBounds(10, 0, 800, 700);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmdSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_cmdSalirActionPerformed

    private void chkPaltaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkPaltaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkPaltaActionPerformed

    private void chkChucrutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkChucrutActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkChucrutActionPerformed

    private void chkSalsaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkSalsaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkSalsaActionPerformed

    private void txtTelefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTelefonoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTelefonoActionPerformed

    private void txtDireccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDireccionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDireccionActionPerformed

    private void rdbNormalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbNormalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdbNormalActionPerformed

    private void cmdPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdPedidoActionPerformed
        String pago ="",
        nombre="",
        direccion = "",
        telefono="",
        sucursal = "",
        ingredientes ="",
        tamano = "";
        
        int monto = 0;
        
        nombre = txtNombre.getText();
        direccion = txtDireccion.getText();
        telefono = txtTelefono.getText();
        sucursal = lstSucursal.getSelectedValue();
        pago = String.valueOf(cmbPago.getSelectedItem());
        
        if (rdbNormal.isSelected()){
            tamano = rdbNormal.getText();
        }
        else{
            if (rdbGrande.isSelected()){
                tamano = rdbGrande.getText();
            }
        }
        
        monto = calculo();
        
        JOptionPane.showMessageDialog(null,
                "Nombre " + nombre +"\nDireccion " + direccion +"\nTelefono " + telefono + "\nMétodo Pago " + pago + "\nIngredientes " +ingredientes + "\nTamaño " + tamano +"\nSucursal "+ sucursal  +"\nMonto " + monto,
                "Pedido" + "\nMonto: " + monto,  1);
    }//GEN-LAST:event_cmdPedidoActionPerformed

    private void cmdVentanaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdVentanaActionPerformed
        String pass = String.valueOf(pswVentana.getPassword());
        
        frmVentana ventana = new frmVentana(pass);
        ventana.setVisible(true);
    }//GEN-LAST:event_cmdVentanaActionPerformed
    
    public int getPrecio(String ingrediente, int cantidad){
        int valor = 0;
        int i = 0;
        boolean encontro = false;
        while (i<4 && encontro == false){
            if (ing[i].equals(ingrediente)){
                encontro = true;
                valor = precio[i] * cantidad;
            }
            i++;
        }
        
        return valor;
    };
    
    public int calculo(){
        
        int monto = 0;
        
        if (chkPalta.isSelected()){
            String ingrediente = chkPalta.getText();
            int cantidad = Integer.parseInt(txtPalta.getText());
            monto = monto + getPrecio(ingrediente, cantidad);
        }
        
        if (chkTomate.isSelected()){
            String ingrediente = chkTomate.getText();
            int cantidad = Integer.parseInt(txtTomate.getText());
            monto = monto + getPrecio(ingrediente, cantidad);
        }
        
        if (chkChucrut.isSelected()){
            String ingrediente = chkChucrut.getText();
            int cantidad = Integer.parseInt(txtChucrut.getText());
            monto = monto + getPrecio(ingrediente, cantidad);
        }
        
        if (chkSalsa.isSelected()){
            String ingrediente = chkSalsa.getText();
            int cantidad = Integer.parseInt(txtSalsa.getText());
            monto = monto + getPrecio(ingrediente, cantidad);
        }
        
        return monto;
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmPedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmPedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmPedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmPedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmPedido().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bgTamano;
    private javax.swing.JCheckBox chkChucrut;
    private javax.swing.JCheckBox chkPalta;
    private javax.swing.JCheckBox chkSalsa;
    private javax.swing.JCheckBox chkTomate;
    private javax.swing.JComboBox<String> cmbPago;
    private javax.swing.JButton cmdPedido;
    private javax.swing.JButton cmdSalir;
    private javax.swing.JButton cmdVentana;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblDireccion;
    private javax.swing.JLabel lblIngredientes;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblPago;
    private javax.swing.JLabel lblTamano;
    private javax.swing.JLabel lblTelefono;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JList<String> lstSucursal;
    private javax.swing.JPasswordField pswVentana;
    private javax.swing.JRadioButton rdbGrande;
    private javax.swing.JRadioButton rdbNormal;
    private javax.swing.JTextField txtChucrut;
    private javax.swing.JTextField txtDireccion;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtPalta;
    private javax.swing.JTextField txtSalsa;
    private javax.swing.JTextField txtTelefono;
    private javax.swing.JTextField txtTomate;
    // End of variables declaration//GEN-END:variables
}
